### ISSUE TITLE
RuntimeError: start (0) + length (120) exceeds dimension size (64).

### ISSUE THREAD

**Issue by wyrde** [BlenderNeko/ComfyUI_TiledKSampler#3]
when using this workflow
[blenderneko cloud_panorama-wyrded.zip](https://github.com/BlenderNeko/ComfyUI_TiledKSampler/files/11412756/blenderneko.cloud_panorama-wyrded.zip)

```
got prompt
making attention of type 'vanilla-pytorch' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-pytorch' with 512 in_channels
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.31s/it]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.30it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.42s/it]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.19it/s]
  3%|██▎                                                                                | 1/35 [00:06<03:31,  6.22s/it]
Traceback (most recent call last):
  File "D:\sd\comfyui\comfy\execution.py", line 195, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
  File "D:\sd\comfyui\comfy\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "D:\sd\comfyui\comfy\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "D:\sd\comfyui\comfy\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  [Previous line repeated 3 more times]
  File "D:\sd\comfyui\comfy\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\comfyui\comfy\custom_nodes\TiledKSampler\nodes.py", line 96, in sample
    slices = [tiling.get_slice(samples, x1,x2,y1,y2) for x1,x2,y1,y2,_ in tiles_batch]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\comfyui\comfy\custom_nodes\TiledKSampler\nodes.py", line 96, in <listcomp>
    slices = [tiling.get_slice(samples, x1,x2,y1,y2) for x1,x2,y1,y2,_ in tiles_batch]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\comfyui\comfy\custom_nodes\TiledKSampler\tiling.py", line 21, in get_slice
    t = tensor.narrow(-2, h, h_len)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: start (0) + length (120) exceeds dimension size (64).
```

**Comment by BlenderNeko** [comment]
should be fixed in #2
