### ISSUE TITLE
AttributeError: 'ControlNet' object has no attribute 'device'

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [BlenderNeko/ComfyUI_TiledKSampler#58]
Hello. 

PixelTiledKSampleUpscalerProviderPipe throws this error.

```

PixelTiledKSampleUpscalerProviderPipe throws this error.

Traceback (most recent call last):
  File "E:\diffusion\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\diffusion\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\diffusion\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\diffusion\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\diffusion\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1315, in doit
    refined_latent = IterativeLatentUpscale().doit(latent, upscale_factor, steps, temp_prefix, upscaler, step_mode, unique_id)
  File "E:\diffusion\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1267, in doit
    current_latent = upscaler.upscale_shape(step_info, current_latent, new_w, new_h, temp_prefix)
  File "E:\diffusion\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 2007, in upscale_shape
    refined_latent = self.tiled_ksample(upscaled_latent, upscaled_images)
  File "E:\diffusion\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 1962, in tiled_ksample
    return TiledKSampler().sample(model, seed, tile_width, tile_height, tiling_strategy, steps, cfg, sampler_name,
  File "E:\diffusion\ComfyUI\custom_nodes\ComfyUI_TiledKSampler\nodes.py", line 326, in sample
    return sample_common(model, 'enable', seed, tile_width, tile_height, tiling_strategy, steps_total, cfg, sampler_name, scheduler, positive, negative, latent_image, steps_total-steps, steps_total, 'disable', denoise=1.0, preview=True)
  File "E:\diffusion\ComfyUI\custom_nodes\ComfyUI_TiledKSampler\nodes.py", line 261, in sample_common
    slice_cnet(tile_h, tile_h_len, tile_w, tile_w_len, m, img)
  File "E:\diffusion\ComfyUI\custom_nodes\ComfyUI_TiledKSampler\nodes.py", line 91, in slice_cnet
    model.cond_hint = hint.to(model.control_model.dtype).to(model.device)
AttributeError: 'ControlNet' object has no attribute 'device'

```

According to this link. This node is not adapted to their last patch https://github.com/comfyanonymous/ComfyUI/issues/5344#issuecomment-2439930017

**Comment by BigZampano** [comment]
Same here, please help..! My favorite workflow doesn't work anymore...

**Comment by arnonmoscona** [comment]
Same here 



# ComfyUI Error Report
## Error Details
- **Node Type:** BNK_TiledKSamplerAdvanced
- **Exception Type:** AttributeError
- **Exception Message:** 'ControlNet' object has no attribute 'device'
## Stack Trace
```
  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TiledKSampler\nodes.py", line 357, in sample
    return sample_common(model, add_noise, noise_seed, tile_width, tile_height, tiling_strategy, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, start_at_step, end_at_step, return_with_leftover_noise, denoise=1.0, preview= preview == 'enable')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TiledKSampler\nodes.py", line 261, in sample_common
    slice_cnet(tile_h, tile_h_len, tile_w, tile_w_len, m, img)

  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TiledKSampler\nodes.py", line 91, in slice_cnet
    model.cond_hint = hint.to(model.control_model.dtype).to(model.device)
                                                            ^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.6-7-gfabf449
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25756696576
  - **VRAM Free:** 14485473214
  - **Torch VRAM Total:** 9495904256
  - **Torch VRAM Free:** 21415870

## Logs
```
2024-11-02 17:26:10,105 - root - INFO - Total VRAM 24564 MB, total RAM 195798 MB
2024-11-02 17:26:10,105 - root - INFO - pytorch version: 2.3.1+cu121
2024-11-02 17:26:10,106 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-02 17:26:10,106 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-11-02 17:26:10,962 - root - INFO - Using pytorch cross attention
2024-11-02 17:26:11,966 - root - INFO - [Prompt Server] web root: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
2024-11-02 17:26:14,439 - root - INFO - Total VRAM 24564 MB, total RAM 195798 MB
2024-11-02 17:26:14,439 - root - INFO - pytorch version: 2.3.1+cu121
2024-11-02 17:26:14,439 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-02 17:26:14,440 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-11-02 17:26:15,987 - root - INFO - --------------
2024-11-02 17:26:15,987 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-11-02 17:26:15,995 - root - INFO - ChatGPT.available True
2024-11-02 17:26:15,996 - root - INFO - edit_mask.available True
2024-11-02 17:26:16,272 - root - INFO - ClipInterrogator.available True
2024-11-02 17:26:16,376 - root - INFO - PromptGenerate.available True
2024-11-02 17:26:16,376 - root - INFO - ChinesePrompt.available True
2024-11-02 17:26:16,376 - root - INFO - RembgNode_.available True
2024-11-02 17:26:16,682 - root - INFO - TripoSR.available
2024-11-02 17:26:16,682 - root - INFO - MiniCPMNode.available
2024-11-02 17:26:16,725 - root - INFO - Scenedetect.available
2024-11-02 17:26:16,728 - root - INFO - FishSpeech.available False
2024-11-02 17:26:16,734 - root - INFO - SenseVoice.available
2024-11-02 17:26:16,752 - root - INFO - Whisper.available False
2024-11-02 17:26:16,758 - root - INFO - FalVideo.available
2024-11-02 17:26:16,758 - root - INFO - [93m -------------- [0m
2024-11-02 17:26:17,264 - root - WARNING - Traceback (most recent call last):
  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\__init__.py", line 1, in <module>
    from .InstantID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 13, in <module>
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'

2024-11-02 17:26:17,264 - root - WARNING - Cannot import C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID module for custom nodes: No module named 'insightface'
2024-11-02 17:26:18,303 - root - INFO - 
Import times for custom nodes:
2024-11-02 17:26:18,303 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\rembg-comfyui-node
2024-11-02 17:26:18,303 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-02 17:26:18,303 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Styles_CSV_Loader
2024-11-02 17:26:18,303 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\tiled_ksampler
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyUI_TJ_NormalLighting
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SimpleMath
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-noisetools
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Video-Matting
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds (IMPORT FAILED): C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-11-02 17:26:18,304 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-02 17:26:18,305 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
2024-11-02 17:26:18,305 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-11-02 17:26:18,305 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-11-02 17:26:18,305 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-02 17:26:18,305 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-11-02 17:26:18,305 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
2024-11-02 17:26:18,305 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-11-02 17:26:18,305 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
2024-11-02 17:26:18,305 - root - INFO -    0.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light
2024-11-02 17:26:18,305 - root - INFO -    0.1 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-11-02 17:26:18,305 - root - INFO -    0.2 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ControlNeXt-SVD
2024-11-02 17:26:18,305 - root - INFO -    0.4 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-02 17:26:18,305 - root - INFO -    0.4 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-11-02 17:26:18,305 - root - INFO -    0.5 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-11-02 17:26:18,305 - root - INFO -    1.0 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-11-02 17:26:18,305 - root - INFO -    1.1 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
2024-11-02 17:26:18,305 - root - INFO -    1.9 seconds: C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes
2024-11-02 17:26:18,305 - root - INFO - 
2024-11-02 17:26:18,315 - root - INFO - Starting server

2024-11-02 17:26:18,316 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-02 17:26:57,083 - root - INFO - got prompt
2024-11-02 17:26:57,215 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-11-02 17:26:57,217 - root - INFO - model_type EPS
2024-11-02 17:26:59,836 - root - INFO - Using pytorch attention in VAE
2024-11-02 17:26:59,838 - root - INFO - Using pytorch attention in VAE
2024-11-02 17:27:01,589 - root - INFO - Requested to load SDXLClipModel
2024-11-02 17:27:01,589 - root - INFO - Loading 1 new model
2024-11-02 17:27:01,820 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-11-02 17:27:02,135 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,136 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,136 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,136 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,136 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,136 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,136 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,136 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,164 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,165 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,166 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-11-02 17:27:02,288 - root - INFO - Requested to load SDXL
2024-11-02 17:27:02,289 - root - INFO - Loading 1 new model
2024-11-02 17:27:03,071 - root - INFO - loaded completely 0.0 4897.0483474731445 True
2024-11-02 17:27:08,067 - root - INFO - Requested to load AutoencoderKL
2024-11-02 17:27:08,067 - root - INFO - Loading 1 new model
2024-11-02 17:27:08,265 - root - INFO - loaded completely 0.0 159.55708122253418 True
2024-11-02 17:27:10,564 - root - INFO - Requested to load ControlNet
2024-11-02 17:27:10,564 - root - INFO - Loading 1 new model
2024-11-02 17:27:10,770 - root - INFO - loaded completely 0.0 2386.120147705078 True
2024-11-02 17:27:10,781 - root - ERROR - !!! Exception during processing !!! 'ControlNet' object has no attribute 'device'
2024-11-02 17:27:10,781 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TiledKSampler\nodes.py", line 357, in sample
    return sample_common(model, add_noise, noise_seed, tile_width, tile_height, tiling_strategy, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, start_at_step, end_at_step, return_with_leftover_noise, denoise=1.0, preview= preview == 'enable')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TiledKSampler\nodes.py", line 261, in sample_common
    slice_cnet(tile_h, tile_h_len, tile_w, tile_w_len, m, img)
  File "C:\Users\arnon\Downloads\graphics\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TiledKSampler\nodes.py", line 91, in slice_cnet
    model.cond_hint = hint.to(model.control_model.dtype).to(model.device)
                                                            ^^^^^^^^^^^^
AttributeError: 'ControlNet' object has no attribute 'device'

2024-11-02 17:27:10,783 - root - INFO - Prompt executed in 13.70 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by arnonmoscona** [comment]
[_tiled_sdxl_large_image.json](https://github.com/user-attachments/files/17608447/_tiled_sdxl_large_image.json)

**Comment by alex-mitov** [comment]
I found that the problem only appears to be happening with the newer versions of ComfyUI. I tried with version 2492 [ 458cd9 ] (2024-08-07) and the TiledKsampler node works fine with it. It appears that something in the new ComfyUI broke compatibility with the node?

**Comment by mkat2** [comment]
> I tried with version 2492 [ 458cd9 ] (2024-08-07) and the TiledKsampler node works fine with it. It appears that something in the new ComfyUI broke compatibility with the node?

Is there any solution yet?

**Comment by phuhl** [comment]
There is a fix in this PR: https://github.com/BlenderNeko/ComfyUI_TiledKSampler/pull/59
